In [5]:
# imported packages
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [27]:
# neural network algorithm
class Neural_Network(object):
    
    # data for start point - inputs, weights and biases
    def __init__(self, data, weights, biases):
        self.data = data
        self.weights = weights
        self.biases = biases
    
    # create new hidden layer - calculate the next layer's neuron's values
    def create_layer(self, data):
        for neuron in data:
            print(neuron)
    
    # create all hidden layers and return the output
    def process():
        output = None
        return output
            
    # for debugging - return the final values of the calculation        
    def __repr__(self):
        return str({
            'data': self.data,
            'weights': self.weights,
            'biases': self.biases
        })

In [28]:
data = tf.constant([1, 1])
weights = tf.constant([[2, 4], [6, 8]])
biases = tf.constant([[0.25, 0.5], [0.75, 1]])
network = Neural_Network(data, weights, biases)
print(network)

{'data': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>, 'weights': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>, 'biases': <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.25, 0.5 ],
       [0.75, 1.  ]], dtype=float32)>}


In [3]:
import numpy as np
layers1 = np.array([[1,2], [3,4]])